Accenture/sfmc-devtools-copado

.vscode/settings.json, copado-function/app/Deploy.js
- closes #88 
- change github vscode extension branch naming scheme
...
=> 88 bug deployjs doesnt stop on no changes found

copado-function/app/Commit.js
Deleted --save as described in ticket
Line 388 at the commit.js
=> deleted --save parameter

copado-function/app/Commit.js
Reverts Accenture/sfmc-devtools-copado#81
=> Revert "deleted --save parameter"

copado-function/app/Commit.js
Reverts Accenture/sfmc-devtools-copado#97
=> Revert "Revert "deleted --save parameter""

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
Changed the credentials in order to store the source and the target
=> changed the credentials on the CONFIG variable

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
- Created a function to check if date is equal to 0001-01-01T00:00:00-06:00, if it is, return "-", if not return the actual date value.
- Added this check on cd (created date) and on ld (last modified date) as well.
- Changed the Copado.uploadToolLogs() to after the Log.error() so we don't need to wait the Copado.uploadToolLogs() to finish to see the actual error.
=> wrong date bug fix

copado-function/app/.eslintrc.json, copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
check commits / changed files pls
=> changes based on nahuel's review & insights

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
=> #120 Result Data and Error Message not getting updated on job execution + result record

.prettierrc
closes #125 
prettier rules updated
=> #125: set tabWidth and printWidth

.sf/config.json, .vscode/settings.json, force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.js
Error Label Appears after several minutes of having refreshed 
The page remains listening to the result platform event even after the function result completed. To fix this unsubscribe from platform event as soon as the result completes and the table is retendered.
...
=> #03 platform event even after the function result completed

.husky/commit-msg, .husky/post-checkout, copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
- closes #127 
- also adds commit message check
=> 127 feature user logresult logerror to properly save status

copado-function/app/Commit.js
=> #135: apply filters on execSync result to get proper array from git diff

force-app/main/default/lwc/marketingCloudCopadoDataTable/marketingCloudCopadoDataTable.js
Catch error message when Retrieve function fails
Err msg "An error occurred while Metadata file Retrieve. please refer to the job id: "
with   job id:         jobExecutionId
...
=> #34  Retrieve function failes

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, copado-function/app/Upgrade.js
changed env variables in retrieve.js, commit.js, deploy.js and upgrade.js
=> #151 update env variables

.sf/config.json
Loading the latest version from GIT solved the issue.
...
...
=> [BUG] Child Env component now lists ALL other environments #145

copado-function/app/Retrieve.js
- set credentialNameTarget to null in CONFIG variable at the retrieve.js
=> #100 put credentialNameTarget: null in the retrieve.js

force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.html
To allow search without clicking or any action  
...
=> #164 immediate search without any action

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js
=> 187 bug if recreate branch is selected and the delete fails we should handle it gracefully

force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
thank you @nrabe-copado
fixes #191 
...
=> #191: only print progress messages for my own jobExecution

copado-function/app/Commit.js, copado-function/app/Deploy.js
closes #177 
_Note:_ This solution was not yet published to copadonull org!
=> 177 feature improve speed of execution for mcdevretrieve with type key combos

force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
we only have jobexecution id but need result id or job step id to filter this.
closes #196 
...
=> #196: reverting prior filter

copado-function/app/Commit.js
=> #205: fix commit result message on windows

copado-function/app/Deploy.js
Added a try catch and changed the log.error to a log.warn with a message saying to check the logs manually because git not updated with the changes.
=> 203 task add the try and catch in deploy commit

copado-function/app/Commit.config, copado-function/app/Promote.config, copado-function/app/Retrieve.js
=> #213 bug automation lastmodifieddate is empty if automation was never changed after creation

copado-function/app/Commit.js
closes #218 
this PR is not the actual fix but its changes helped get the right logs
=> #218: ensuring mcdev logs are uploaded in case of error

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js
- Changed the string so it shows the number of items on the result of deploy and commit scripts
- changed the string on the retrieve to display "items" instead of "elements"
=> 219 task make every result message similar

copado-function/app/Retrieve.js
=> #223: retrieve assets with subtypes

copado-function/app/Commit.js
Added a map that changes the type to the correct form
=> #225 fixing not valid metadata on commit.js

copado-function/app/Commit.js, copado-function/app/Deploy.js
=> #237: remove subtype for mcdev-methods not supporting it

copado-function/app/Commit.config, copado-function/app/Commit.js, copado-function/app/Deploy.config, copado-function/app/Deploy.js, copado-function/app/Retrieve.config, copado-function/app/Retrieve.js, copado-function/app/environments/Commit.env-sample, copado-function/app/environments/Deploy.env-sample, copado-function/app/environments/Retrieve.env-sample, copado-function/app/images/Dockerfile
- Changed retreive, commit and deploy.js to use the global mcdev tools previously installed if got an environment variable isMcdevInstalledGlobally = 'true', if not, run as it was before
- Changed the .config files for retrieve, commit and deploy as well
- update the image docker at copado > function > configuration > image name field to the one Nahuel gave us (with the mcdev globally installed).
- Added dockerfile in the copado-function/app/images
=> 17 feature docker container that has dependencies preinstalled

copado-function/app/Retrieve.js
=> #240 fix regexp expression

copado-function/app/Deploy.js
=> #242: fix no-mcdev-logs if deploy-verification failed

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js, force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
- fixes #231
- reduce log.progress spam
- don't print npm/git/node version unless in debug mode
=> #231 bug infinite time spinner if no records to show

copado-function/app/Commit.js, copado-function/app/Deploy.config, copado-function/app/Deploy.js, copado-function/app/environments/Commit.env-sample, copado-function/app/environments/Deploy.env-sample
=> 257 feature take u param of copado deploy changesjson to enhance commit msg for target

copado-function/app/Commit.config, copado-function/app/Commit.js, copado-function/app/Deploy.config, copado-function/app/Deploy.js, copado-function/app/Retrieve.config, copado-function/app/Retrieve.js, force-app/main/default/applications/mcdo_contributor.app-meta.xml, force-app/main/default/classes/mcdo_ChildEnvironmentVariables.cls, force-app/main/default/classes/mcdo_GetPropertiesOfUSsInPromotion.cls, force-app/main/default/classes/mcdo_GetPropertiesOfUSsInPromotion.cls-meta.xml, force-app/main/default/classes/mcdo_SourceChildEnvironmentVariables.cls, force-app/main/default/classes/mcdo_SourceChildEnvironmentVariables.cls-meta.xml, force-app/main/default/classes/mcdo_SourceEnvironmentVariables.cls, force-app/main/default/classes/mcdo_SourceEnvironmentVariables.cls-meta.xml, force-app/main/default/flexipages/Environment_Record_Page1.flexipage-meta.xml, force-app/main/default/layouts/copado__Environment__c-copado__Environment Layout.layout-meta.xml, force-app/main/default/permissionsets/Copado_Marketing_Cloud.permissionset-meta.xml
=> 204 bug deploy to secondary targets fails if file was renamed during deploy from dev to qa

copado-function/app/Commit.js, copado-function/app/Deploy.js, copado-function/app/Retrieve.js
=> #249: clean up logs

copado-function/app/images/Dockerfile
=> #265: upgrade docker file to use mcdev 4.1.1

copado-function/app/Retrieve.js, copado-function/app/images/Dockerfile, force-app/main/default/lwc/mcdo_RetrieveTable/mcdo_RetrieveTable.js
closes #211 
dependent on https://github.com/Accenture/sfmc-devtools/pull/499
=> 211 bug retrieve in retrievetable should return folders

copado-function/app/Deploy.js
=> #274: ensuring we use the child-source-market for deployNTimes

copado-function/app/Deploy.js, force-app/main/default/classes/mcdo_SourceChildEnvironmentVariables.cls
=> 276 bug source child envvars not retrieve from child of child during deploy

copado-function/app/Deploy.js
=> 279 bug deploy1ton fails to push the generated target files to git

copado-function/app/Deploy.js
Added an IF to see if the targetMID === sourceMID then use the key without ending on the MID
=> 288 bug deploy asset failing from parent bu to another when adding the number to the key
